module.exports = {
  semi: true,
  trailingComma: 'all',
  singleQuote: true,
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  jsxSingleQuote: false,
  arrowParens: 'always',
  endOfLine: 'lf',

  importOrder: [
    '^(react/(.*)$)|^(react$)',
    '^(next/(.*)$)|^(next$)',
    '',
    '<BUILTIN_MODULES>',
    '<THIRD_PARTY_MODULES>',
    '',
    '^(@/types/(.*)$)|^(@/types$)',
    '',
    '^(@/fonts/(.*)$)|^(@/fonts$)',
    '^(@/config/(.*)$)|^(@/config$)',
    '^(@/auth/(.*)$)|^(@/auth$)',
    '^(@/lib/(.*)$)|^(@/lib$)',
    '^(@/hooks/(.*)$)|^(@/hooks$)',
    '^(@/actions/(.*)$)|^(@/actions$)',
    '',
    '^@/components/ui/(.*)$',
    '^@/components/(.*)$',
    '^@/registry/(.*)$',
    '',
    '^@/app/(.*)$',
    '',
    '^(?!.*[.]css$)[./].*$',
    '.css$',
  ],

  plugins: [
    'prettier-plugin-tailwindcss',
    '@ianvs/prettier-plugin-sort-imports',
  ],
};
